apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  selector:
    matchLabels:
      app: node
  replicas: 3
  template: 
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: dini1/eng89_node_app
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: mongodb://mongo:27017/posts
          command: ["/bin/sh","-c"]
          args: ["node","seeds/seed.js"]
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: node
spec:
  selector:
    app: node
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer    

# Scale our app - hpa to scale our deployment on demand
# in the config we need to declare min number of pods and max number of pods.
# create a file called node_hpa.yml
